ktor:
  application:
    modules:
       - com.probro.khoded.ApplicationKt.module
    deployment:
      port:
        -8080
  storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/khodedBackend"
    user: "postgres"
    password: "password"